# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 824f76c90f6c4508aca57ddbab187aac3aa9d68ef81edfd2ea315112779389fb1f7b5628b99c888ab4be508e28b5f963016d55531015a5112dacc34320bba3bf

test:
  secret_key_base: 03a6f21b22b1e25bdc2bc07875fd47f046c5d7a754320c6bf2bef6da9c7a31f24dc478d38f1eb13c8634b4e7f252a9d7ca677034dbab5fe2e479c9dcd2fa8181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
